# Generated by Django 3.1.4 on 2022-09-09 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0002_auto_20220908_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=1, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('osm_id_2', models.IntegerField(blank=True, null=True)),
                ('name_2', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cafe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=1, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('osm_id_2', models.IntegerField(blank=True, null=True)),
                ('name_2', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'fastfood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=1, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('osm_id_2', models.IntegerField(blank=True, null=True)),
                ('name_2', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('layer', models.CharField(blank=True, max_length=1, null=True)),
                ('path', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=1, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('osm_id_2', models.IntegerField(blank=True, null=True)),
                ('name_2', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
    ]
